### ISSUE TITLE
Book's author is not show author name but something other

### ISSUE THREAD

**Issue by Walsh000** [nekon0/SoWePray#18]
![image](https://user-images.githubusercontent.com/90783499/194469341-a115ea50-f5f4-42a8-bc7c-b7ed031503c0.png)

**Comment by nyoisy88** [comment]
Thuộc tính book.author ban đầu đã đổi sang thuộc tính object author của book nên hiển thị là 1 object
T sẽ sửa lại trong commit tiếp
