### ISSUE TITLE
[High][Major] Click "Rate" button without select rate lead to error 500

### ISSUE THREAD

**Issue by Walsh000** [nekon0/SoWePray#26]
https://user-images.githubusercontent.com/90783499/199411958-c3305098-7893-4096-97de-ddca7183dc50.mp4

**Comment by nyoisy88** [comment]
Fixed in book-detail.jsp

**Comment by Walsh000** [comment]
> Fixed in book-detail.jsp

Still error in both book detail and novel detail

**Comment by nyoisy88** [comment]
Yes

**Comment by Walsh000** [comment]
@nekon0 It still error when click near rate selection. Only book detail. Novel detail is good.

https://user-images.githubusercontent.com/90783499/201524929-28ecea70-ad1c-4f9c-8f5d-3444721230ce.mp4

**Comment by Walsh000** [comment]
@nekon0 Fixed. Merge from my branch, pls
