### ISSUE TITLE
[High][Major] Arrange chapter button on TOC screen lead to 404 error

### ISSUE THREAD

**Issue by Walsh000** [nekon0/SoWePray#27]
https://user-images.githubusercontent.com/90783499/201461027-c3ae8a3c-0a15-4e97-804c-a5589110e311.mp4

**Comment by Walsh000** [comment]
![image](https://user-images.githubusercontent.com/90783499/201485193-33b4876e-39f8-4fe3-9f23-9676f01b2231.png)
Same with admin's TOC

**Comment by nyoisy88** [comment]
Chức năng chưa implement. Đã xóa.
