### ISSUE TITLE
[Low][Minor]Cannot edit comment or reply other reply in own comment

### ISSUE THREAD

**Issue by Walsh000** [nekon0/SoWePray#34]
https://user-images.githubusercontent.com/90783499/201483893-2654d54a-a8ce-45bc-a011-d6f5fa3b9b1c.mp4

**Comment by Walsh000** [comment]
Cannot edit comment, cause by length of it. It works if I post a short comment

**Comment by nyoisy88** [comment]
Lạ nhỉ t làm bth mà?

**Comment by Walsh000** [comment]
> Lạ nhỉ t làm bth mà?
Bây giờ lại được r. Oke nhé.
