### ISSUE TITLE
[Medium][Minor] Home button in book reading screen not working

### ISSUE THREAD

**Issue by Walsh000** [nekon0/SoWePray#35]
https://user-images.githubusercontent.com/90783499/201485098-c8262de8-005b-4dc6-97c2-e64aaba99a94.mp4

**Comment by nyoisy88** [comment]
Đã fix cả tiêu đề lẫn tên tác giả.

**Comment by Walsh000** [comment]
> Đã fix cả tiêu đề lẫn tên tác giả.

Cái tiêu đề vs tên tác giả là t test sửa đi mà
