### ISSUE TITLE
[Medium][Minor] Admin's user management not show all users

### ISSUE THREAD

**Issue by Walsh000** [nekon0/SoWePray#36]
![image](https://user-images.githubusercontent.com/90783499/201486145-059c9513-0160-4acb-be6c-5e8a74cbe966.png)

**Comment by Walsh000** [comment]
@baspdd

**Comment by baspdd** [comment]
only display special user with recentl actions : purchase , report

**Comment by Walsh000** [comment]
> only display special user with recentl actions : purchase , report

Why only those users need to be managed?

**Comment by Walsh000** [comment]
Close.
