### ISSUE TITLE
[Low][Low]Clearing author's name is so easy

### ISSUE THREAD

**Issue by Walsh000** [nekon0/SoWePray#37]
https://user-images.githubusercontent.com/90783499/201486343-dc4467dd-b433-49fe-9dba-96cc3cfd4809.mp4

**Comment by Walsh000** [comment]
@baspdd

**Comment by baspdd** [comment]
chỉ fix thành ấn mà nó không thành rỗng thôi hở

**Comment by Walsh000** [comment]
Uhm chỉ thế thôi

Vào 02:27, CN, 13 Th11, 2022 Phạm Đức Duy ***@***.***> đã
viết:

**Comment by baspdd** [comment]
thế done r

**Comment by Walsh000** [comment]
@nekon0 Alo alo merge vào đi

**Comment by nyoisy88** [comment]
Done
