### ISSUE TITLE
[Medium][Minor] Forget password - Send email connection error

### ISSUE THREAD

**Issue by Walsh000** [nekon0/SoWePray#39]
https://user-images.githubusercontent.com/90783499/201486991-64f7e897-f760-4168-98cf-f054aa6121d2.mp4

**Comment by Walsh000** [comment]
@nekon0  Có khả năng do mạng chỗ t. Nếu bên m vẫn connect demo bình thường thì bỏ qua nhé

**Comment by nyoisy88** [comment]
Nhập user và pass vào web.xml mới gửi đc nhá

**Comment by nyoisy88** [comment]
Ngoài ra còn phải cài đặt cho phép ứng dụng kém an toàn truy cập nên cái này để t demo là đc.
Ko quên tắt là spam đầy mail đấy

**Comment by Walsh000** [comment]
> Ngoài ra còn phải cài đặt cho phép ứng dụng kém an toàn truy cập nên cái này để t demo là đc. Ko quên tắt là spam đầy mail đấy

Ok
