### ISSUE TITLE
Nothing different after user send a ticket to admin

### ISSUE THREAD

**Issue by Walsh000** [nekon0/SoWePray#42]
https://user-images.githubusercontent.com/90783499/201521872-96a8e334-3726-4d48-8b37-93f78bbd115f.mp4

@baspdd

**Comment by Walsh000** [comment]
https://user-images.githubusercontent.com/90783499/201522649-875ab67c-3ea6-4f57-9ee5-04665b16fdfc.mp4

After that, when login by this account, this user become admin

**Comment by baspdd** [comment]
gửi t cái db m test với

**Comment by Walsh000** [comment]
Chắc do lỗi db. Sau khi reset đã chạy ổn. Tạm close trước. Nếu lại bị thì mở lại sau.
