### ISSUE TITLE
Novel's add to favor and report button not working

### ISSUE THREAD

**Issue by Walsh000** [nekon0/SoWePray#46]
https://user-images.githubusercontent.com/90783499/201526280-2b044f5f-9d5c-48df-973e-d5950af323cb.mp4

@nekon0

**Comment by Walsh000** [comment]
@nekon0 Alo làm nhanh cái này thôi lead ơi

**Comment by Walsh000** [comment]
https://user-images.githubusercontent.com/90783499/201529637-47f60f1f-9735-47a9-876a-4b502e056ae0.mp4

Nhầm video

**Comment by nyoisy88** [comment]
Đã fix js
